global:
  resolve_timeout: 5m

route:
  group_by: ["alertname", "container_name"]
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 4h
  receiver: "slack-notifications"

receivers:
  - name: "slack-notifications"
    slack_configs:
      - api_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
        channel: "#development-alerts"
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        actions:
          - type: button
            text: "View in Grafana"
            url: "{{ .CommonAnnotations.grafana_url }}"
            style: '{{ if eq .CommonLabels.severity "critical" }}danger{{ else }}default{{ end }}'

templates:
  - "/etc/alertmanager/template/*.tmpl"
