# 使用 Node.js 18 作为基础镜像
FROM node:18-alpine

# 设置工作目录
WORKDIR /app

# 设置环境变量
ENV NODE_ENV=development
ENV VITE_API_URL=http://localhost:5000
ENV DEBUG=vite:*
# 设置较大的轮询间隔，减少不必要的刷新
ENV CHOKIDAR_INTERVAL=5000
# 忽略特定目录的变更
ENV VITE_IGNORED_DIRS="['../../docs/**/*.md','**/node_modules/**','**/dist/**']"

# 复制 package.json 和 package-lock.json
COPY package*.json ./

# 安装依赖
RUN npm install --registry=https://registry.npmmirror.com
RUN npm install markdown-it github-markdown-css --registry=https://registry.npmmirror.com

# 复制源代码
COPY . .

# 暴露端口
EXPOSE 3000

# 启动开发服务器
CMD ["npm", "run", "dev"] 